# Generated by Django 5.2.1 on 2025-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default_photo.png', null=True, upload_to='avatars/', verbose_name='Фото профиля'),
        ),
    ]
